import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"

import { PageContextProvider } from "@/context"
import { Header, RootLayout } from "@/components"
import { MainWrapper } from "@/components/ui"

// Load custom font //
const font = localFont({
	variable: "--font-primary",
	src: [
		{
			path: "../../public/fonts/PPSupplySans-Regular.otf",
			weight: "400",
		},
		{
			path: "../../public/fonts/PPSupplySans-Ultralight.otf",
			weight: "200",
		},
	],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function Layout({ children }: { children: React.ReactNode }) {
	return (
		<RootLayout>
			<body
				className={`${font.className} w-full max-width-wrapper h-full min-h-full overflow-x-clip`}
			>
				<PageContextProvider>
					<Header />
					<MainWrapper>{children}</MainWrapper>
				</PageContextProvider>
			</body>
		</RootLayout>
	)
}
